export const SITE_CONFIG = {
  name: 'RÜÇHANOĞLU NAKLİYAT',
  shortName: 'RÜÇHANOĞLU',
  tagline: 'Asansörlü Evden Eve Nakliyat',
  url: 'https://www.trakyanakliyatistanbul.com',
  phone: '0544 999 34 66',
  phoneHref: 'tel:05449993466',
  whatsapp: 'https://wa.me/905449993466',
  email: 'trakyanakliyatistanbul@gmail.com',
  emailHref: 'mailto:trakyanakliyatistanbul@gmail.com',
  instagram: 'https://www.instagram.com/',
  youtube: 'https://www.youtube.com/',
  instagramHandle: '@trakyanakliyatistanbul',
  address: 'Beylikdüzü, İstanbul',
  workingHours: 'Pzt–Paz · 07:00–22:00',
  googleRating: '4.9',
  googleReviewCount: '150+',
  foundedYear: 1994,
  experience: '20+ Yıl Deneyim',
} as const

export const COLORS = {
  navy: '#0D1B2A',
  navyMid: '#16263D',
  navyCta: '#112034',
  navyCard: '#1C304E',
  gold: '#B88C3B',
  goldBright: '#B88C3B',
  goldDeep: '#AD7A31',
} as const
